sudo: false

language: java

jdk: oraclejdk8

services: docker

cache:
    apt: true
    pip: true
    directories:
        - $HOME/.m2
            
env:
  global:
    - MAVEN_OPTS="-client -Xms512m -Xmx2048m"
